version: "2"
services:
  backend:
    build: ./api-backend
    restart: always
  frontend:
    build: ./api-frontend
    environment:
      API_BACKEND_URL: backend
      API_BACKEND_PORT: 8001
    restart: always
    depends_on:
      - backend
    ports: 
      - "8000:8000"


